typedef enum FTDI_ERRORS {
    FTDI_NEW_FAILED=1,
    FTDI_USB_OPEN_FAILED=2,
    FTDI_SET_BAUDRATE_FAILED=3,
    FTDI_READ_DATA_FAILED=4 } FTDI_ERRORS; 

const int FTDI_VID=0x0403;
const int FTDI_PID=0x6001;
